management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    instance:
      preferIpAddress: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  ignored-services: '*'
  routes:
    bloggio:
      path: /api/bloggio/**
      url: http://localhost:8083/
      predicates:
        Header=X-Request-Id, \d+

spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: zuulserver
server:
  port: '8111'
