eureka:
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
spring:
  application:
    name: servicediscovery
server:
  port: '8761'